version: "3"
services:
  postgresql:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres

  sonarqube:
    image: bitnami/sonarqube:latest
    ports:
      - "9999:9000"
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_ROOT_USER=sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=sonarqube
      - SONARQUBE_DATABASE_NAME=sonarqube
      - SONARQUBE_DATABASE_USER=sonarqube
      - SONARQUBE_DATABASE_PASSWORD=sonarqube
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
