version: "3"

services:
  mongo:
    image: mongo:7.0.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: estrut_db
      MONGO_INITDB_ROOT_PASSWORD: aVDxqNF2M1UUKCzc
